database/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='members/'), name='homepage-redirect'),
    url(r'^members/', include('nwbb_members.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, {'template_name': 'nwbb_members/login.html'}),
    url(r'^logout/$', auth_views.logout, {'next_page': '/login/'} , name='logout'),
    url(r'^', include('django.contrib.auth.urls')),
]

nwbb_members/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

app_name = 'members'

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^view_members/$', views.view_members, name='view_members'),
    url(r'^add_user/$', views.add_user, name='add_user'),
    url(r'^edit_member_details/(?P<user_id>\d+)/$', views.edit_member_details, name='edit_member_details'),
    url(r'^view_member_details/(?P<user_id>\d+)/$', views.view_member_details, name='view_member_details'),
    url(r'^edit_user/(?P<user_id>\d+)/$', views.edit_user, name='edit_user'),
    url(r'^access_denied/', TemplateView.as_view(template_name="nwbb_members/access_denied.html")),
    url(r'^$', views.index, name='index'),
    url(r'^add_driving_offences/(?P<user_id>\d+)/$', views.add_driving_offences, name='add_driving_offences'),
    url(r'^add_training/(?P<user_id>\d+)/$', views.add_training, name='add_training'),
]

nwbb_members/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


class RoleType(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    
    def __unicode__(self):
        return self.name
    
class Member(models.Model):
    user = models.OneToOneField(User, related_name="profile")
    id_number = models.CharField(max_length=50, blank=False)
    address_one = models.CharField(max_length=100, blank=True)
    address_two = models.CharField(max_length=50, blank=True)
    town = models.CharField(max_length=100, blank=True)
    county = models.CharField(max_length=50, blank=True)
    post_code = models.CharField(max_length=9, blank=False)
    home_tel = models.CharField(max_length=25, blank=True)
    mobile_tel = models.CharField(max_length=25, blank=True)
    email_shared = models.BooleanField(default=True)
    roles = models.ManyToManyField(RoleType, related_name="member_roles", blank=True)
    comments = models.CharField(max_length=200, blank=True)
    driver_license_number = models.CharField(max_length=100, blank=True)
    driver_license_expiry_date = models.DateField(null=True, blank=True)
    bike_registration = models.CharField(max_length=100, blank=True)

    def __unicode__(self):
        return self.user.get_full_name()

class DrivingOffence(models.Model):
    code = models.CharField(max_length=10, blank=False)
    name= models.CharField(max_length=200, blank=False)
    min_points = models.IntegerField(blank=True)
    max_points = models.IntegerField(blank=True)
    duration = models.IntegerField()
    DURATION_DETAILS = (
        ('DOO','Depending on Offence'),
        ('DOC','Depending on Conviction'),                     )
    duration_details = models.CharField(max_length=3, choices = DURATION_DETAILS, blank=True)
    
    def __unicode__(self):
        return self.code   + " " + self.name + " (" + str(self.min_points) + "-" + str(self.max_points) + " points)"  
                             
class MemberDrivingOffence(models.Model):
    member = models.ForeignKey(User, related_name="member_offence")
    code = models.ForeignKey(DrivingOffence, related_name="offences", blank=False, null=False)
    date = models.DateField()
    points = models.IntegerField()
    
    def __unicode__(self):
        return self.code.code + " - " + self.code.name + " - " + str(self.points) + " point(s)"
    
    def clean(self): 
        if self.date :
            if self.date > date.today():
                raise ValidationError({'date': _('The date cannot be in the future.')})
        
        if self.points and self.code_id is not None:
            if self.points < self.code.min_points:
                raise ValidationError({'points': _('Points cannot be less than the minimum for the offence.')})
        
            if self.points > self.code.max_points:
                raise ValidationError({'points': _('Points cannot be more than the maximum for the offence.')})

class Training(models.Model):   
    name = models.CharField(max_length=200, blank=False)
    description = models.TextField(blank=True, null=True)
    
    def __unicode__(self):
        return self.name
        
class MemberTraining(models.Model):
    member = models.ForeignKey(User, related_name="member_training")
    training = models.ForeignKey(Training, related_name="member_training", blank=False, null=False)
    date_completed = models.DateField(blank=True, null=True)
    expiry_date = models.DateField(blank=True, null=True)
    awarded_by = models.CharField(max_length=200, blank=True, null=True)
    
    def __unicode__(self):
        return self.training.name
        
    def clean(self): 
        if self.date_completed :
            if self.date_completed > date.today():
                raise ValidationError({'date_completed': _('The date cannot be in the future.')})

nwbb_members/forms.py
from django import forms
from django.forms import ModelForm
from nwbb_members.models import Member, MemberDrivingOffence, DrivingOffence,\
    Training, MemberTraining
from django.contrib.auth.models import User

    
class MemberForm(ModelForm):   
    class Meta:      
        model = Member
        fields = ['id_number', 'address_one','address_two','town','county','post_code','home_tel','mobile_tel','email_shared', 'driver_license_number','driver_license_expiry_date','comments', 'roles']
    
class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username')

class OffenceForm(ModelForm):
    code = forms.ModelChoiceField(queryset=DrivingOffence.objects.order_by('code'), label="Driving Offence", to_field_name="code")
    date = forms.DateField(widget=forms.SelectDateWidget())
    
    class Meta:
        model = MemberDrivingOffence        
        fields =('date','code', 'points')

class TrainingForm(ModelForm):
    training = forms.ModelChoiceField(queryset=Training.objects.order_by('name'), label="Training/Qualification")
    date_completed = forms.DateField(widget=forms.SelectDateWidget())
        
    class Meta:
        model = MemberTraining        
        fields =('training', 'date_completed', 'expiry_date','awarded_by')

nwbb_members/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponseRedirect
from django.template.context import RequestContext
from django.core.urlresolvers import reverse
from  .models import Member, MemberDrivingOffence, MemberTraining
from nwbb_members.forms import MemberForm, UserForm, OffenceForm, TrainingForm
from database.tools import random_word
from database.utility import can_view_member, can_add_member, check_member_roles


@login_required
def index(request):
    return render(request, 'nwbb_members/index.html', {'username':request.user.username})
    
@login_required
@user_passes_test(can_view_member, "/members/access_denied", None)
def view_members(request):
    lookup = request.GET.get('lookup') if request.GET.get('lookup') else None
    members = Member.objects.all()
    if lookup:
        name_parts = lookup.split(' ')
        if len(name_parts) == 2:
            members = members.filter(Q(user__first_name__istartswith=name_parts[0]) &
                                       Q(user__last_name__istartswith=name_parts[1]))
        elif len(name_parts) == 1:
            members = members.filter(Q(user__first_name__istartswith=name_parts[0]) |
                                      Q(user__last_name__istartswith=name_parts[0]))
    return render(request, "nwbb_members/view_members.html", {'latest_member_list' : members})

@login_required
@user_passes_test(can_view_member, "/members/access_denied", None)
def view_member_details(request, user_id):
    member = get_object_or_404(User, pk=user_id)
    response_dict = {'member': member} 
    response_dict['request.user']= request.user
    response_dict['can_view_all']= check_member_roles(request.user, ['Committee Member','Trustee','Membership Secretary','Recruitment Manager'])
    response_dict['can_view_partial_postcode']= check_member_roles(request.user, ['Rider','Examiner','Controller'])
    response_dict['can_view_full_postcode']=check_member_roles(request.user, ['Area Manager','Controller Manager'])    
    response_dict['can_view_comments']=check_member_roles(request.user, ['Deputy Area Manager','Area Manager','Controller Manager'])
    response_dict['can_view_bike_reg']=check_member_roles(request.user, ['Deputy Area Manager','Area Manager','Controller Manager'])
    response_dict['driving_offences']=MemberDrivingOffence.objects.filter(Q(member=member)).order_by('-date')
    response_dict['training']=MemberTraining.objects.filter(Q(member=member)).order_by('-date_completed')
    return render_to_response('nwbb_members/view_member_details.html', response_dict, context_instance=RequestContext(request))

@login_required
@user_passes_test(can_add_member,"/members/access_denied", None )
def edit_member_details(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    response_dict = {'member': user.profile}
    if request.method == 'POST':
        form = MemberForm(request.POST, instance=user.profile)
        response_dict['form'] = form
        if form.is_valid():
            form.save()
            if 'return_url' in request.GET:
                return HttpResponseRedirect(request.GET['return_url'])
            else:
                return HttpResponseRedirect(reverse("members:view_member_details", kwargs={'user_id':user_id}))
    else:            
        form = MemberForm(instance=user.profile)
        response_dict['form'] = form
    return render_to_response('nwbb_members/edit_member_details.html', response_dict,
                             context_instance=RequestContext(request))
    
@login_required
@user_passes_test(can_add_member, "/members/access_denied", None)
def add_user(request):
    response_dict = {}
    if request.method == 'POST': 
        form = UserForm(request.POST)
        response_dict['form'] = form
        if form.is_valid():
            new_user = form.save()
            new_user.password = make_password(random_word(18))
            new_user.save()
            Member(user=new_user).save()
            return HttpResponseRedirect(reverse("members:edit_member_details", kwargs={'user_id':new_user.id}))
    else:
        form = UserForm()
        response_dict['form'] = form
    return render_to_response('nwbb_members/add_user.html', response_dict, context_instance=RequestContext(request))

@login_required
@user_passes_test(can_add_member, "/members/access_denied", None)
def edit_user(request, user_id):
    member = get_object_or_404(User, pk=user_id)
    response_dict = {'member': member}
    if request.method == 'POST':  # If the form has been submitted...
        form = UserForm(request.POST, request.FILES, instance=member.profile)  # A form bound to the POST
        response_dict['form'] = form
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("members:view_member_details", args=(member.id)))
    else:
        form = UserForm(instance=member.profile)
        response_dict['form'] = form
    return render_to_response('nwbb_members/edit_user.html', response_dict, context_instance=RequestContext(request))

@login_required
def add_driving_offences(request, user_id):
    member = get_object_or_404(User, pk=user_id)
    response_dict = {'member': member}
    if request.method == 'POST': 
        form = OffenceForm(request.POST)
        response_dict['form'] = form
        if form.is_valid():
            offence = MemberDrivingOffence(member=member, code=form.cleaned_data['code'],
                date=form.cleaned_data['date'], points=form.cleaned_data['points'])
            offence.save()
            return HttpResponseRedirect(reverse("members:view_member_details", args=(member.id,)))
    else:
        form = OffenceForm(instance=member.profile)
        response_dict['form'] = form
    return render_to_response('nwbb_members/add_driving_offences.html', response_dict, context_instance=RequestContext(request))

@login_required
def add_training(request, user_id):
    member = get_object_or_404(User, pk=user_id)
    response_dict = {'member': member}
    if request.method == 'POST': 
        form = TrainingForm(request.POST)
        response_dict['form'] = form
        if form.is_valid():
            training = MemberTraining(member=member, training=form.cleaned_data['training'],
                date_completed=form.cleaned_data['date_completed'], expiry_date=form.cleaned_data['expiry_date'],
                awarded_by=form.cleaned_data['awarded_by'])
            training.save()
            return HttpResponseRedirect(reverse("members:view_member_details", args=(member.id,)))
    else:
        form = TrainingForm(instance=member.profile)
        response_dict['form'] = form
    return render_to_response('nwbb_members/add_training.html', response_dict, context_instance=RequestContext(request))

nwbb_members/templates/nwbb_members/access_denied.html
<!DOCTYPE html>
<html lang="en">
	<head>
    	{%  include "nwbb_members/head.html" %}
	</head>
	<body>
	    <div class="container">
	    	<header>
				<a href="{% url 'members:index' %}"><img src="/static/logo.png" /></a>
			</header>	    
			<hr />
		   <p class="lead"><big>Access Denied </big></p>
		   <p>You do not have access to this functionality.</p>
		    <hr />
	   
		    <!-- 'url' template tag takes the name of the URL pattern
		         as an argument and renders the URL path. Here it renders
		         the path to the logout URL.
		    -->
		    <div class="row">
				 <a href="{% url 'members:index' %}" class="btn btn-lg btn-default" role="button" >Home</a>
			     <a href="{% url 'logout' %}" class="btn btn-lg btn-primary" role="button" >Logout</a>
		     </div>
	     </div>
	</body>
</html>

nwbb_members/templates/nwbb_members/add_driving_offences.html
{% load bootstrap %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "nwbb_members/head.html" %}
</head>
<body>
<div id="wrapper">
    {% include "nwbb_members/nav.html" %}
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Add a Driving Offence for {{ member.get_full_name }}</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Enter the Driving Offence Details
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <form class="form" method="POST">
                                    {% csrf_token %}
                                    {{ form|bootstrap }}
                                    <div class="form-actions">
                                        <button type="submit" class="btn btn-default">Submit Button</button>
                                        <button type="reset" class="btn btn-default">Reset Button</button>
                                    </div>
                                    <script>
					                    $(function() {
					                        $( "#id_date" ).datetimepicker( $.datepicker.regional[ "en-GB" ] );
					                    });
                					</script>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> <!-- /container -->
</body>
</html>

nwbb_members/templates/nwbb_members/add_training.html
{% load bootstrap %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "nwbb_members/head.html" %}
</head>
<body>
<div id="wrapper">
    {% include "nwbb_members/nav.html" %}
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Add Training/Qualifications for {{ member.get_full_name }}</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Enter the Training Details
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <form class="form" method="POST">
                                    {% csrf_token %}
                                    {{ form|bootstrap }}
                                    <div class="form-actions">
                                        <button type="submit" class="btn btn-default">Submit Button</button>
                                        <button type="reset" class="btn btn-default">Reset Button</button>
                                    </div>
                                    <script>
					                    $(function() {
					                        $( "#id_date" ).datetimepicker( $.datepicker.regional[ "en-GB" ] );
					                    });
                					</script>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> <!-- /container -->
</body>
</html>

nwbb_members/templates/nwbb_members/add_user.html
{% load bootstrap %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include "nwbb_members/head.html" %}
</head>
<body>
<div id="wrapper">
    {% include "nwbb_members/nav.html" %}
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Add a New Member</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Enter the Member's Details
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <form class="form" method="POST">
                                    {% csrf_token %}
                                    {{ form|bootstrap }}
                                    <div class="form-actions">
                                        <button type="submit" class="btn btn-default">Submit Button</button>
                                        <button type="reset" class="btn btn-default">Reset Button</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> <!-- /container -->
</div>
</body>
</html>

nwbb_members/templates/nwbb_members/edit_member_details.html
{% load bootstrap %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include "nwbb_members/head.html" %}
</head>
<body>
<div id="wrapper">
    {% include "nwbb_members/nav.html" %}
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Edit Details for {{ member.user.get_full_name }}</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <form class="form" method="POST">
                                    <p>Member's details are displayed below. If anything is incorrect, please make the
                                        appropriate
                                        changes.</p>
                                    <hr/>
                                    {% csrf_token %}
                                    {{ form|bootstrap }}
                                    <hr>
                                    <div class="form-actions">
                                        <button class="btn btn-primary" type="submit">Confirm Details</button>
                                        <a class="btn" href="{% url 'members:index' %}">Cancel</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div> <!-- /container -->
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

nwbb_members/templates/nwbb_members/head.html
<title>NWBB Members Site</title>
<meta charset="utf-8">
<meta name="description" content="">
<meta name="author" content="">

<script src="/static/js/jquery.js" type="application/javascript"></script>
<script src="/static/js/bootstrap.js" type="application/javascript"></script>

<link href="/static/css/bootstrap.css" rel="stylesheet">	
<link href="/static/css/bootstrap.min.css" rel="stylesheet">
<link href="/static/css/style.css" rel="stylesheet">

<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

<script src="//cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js"></script>
<script src="//cdn.datatables.net/1.10.11/js/dataTables.bootstrap.min.js"></script>
<link href="//cdn.datatables.net/1.10.11/css/dataTables.bootstrap.min.css" rel="stylesheet">

<!-- Theme Components -->
<link href="/static/theme/css/sb-admin-2.css" rel="stylesheet">
<link href="/static/theme/css/metisMenu.css" rel="stylesheet">

<script src="/static/theme/js/metisMenu.js" type="application/javascript"></script>
<script src="/static/theme/js/sb-admin-2.js" type="application/javascript"></script>

nwbb_members/templates/nwbb_members/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "nwbb_members/head.html" %}
</head>
<body>
<div id="wrapper">
    {% include "nwbb_members/nav.html" %}
    <div id="page-wrapper">
        <header>
            <a href="{% url 'members:index' %}"><img src="/static/logo.png"/></a>
        </header>
        <hr/>
        <p class="lead text-center">Welcome to the NWBB Members site.</p>
        <hr/>
    </div>
</div>
</body>
</html>

nwbb_members/templates/nwbb_members/login.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{%  include "nwbb_members/head.html" %}
	</head>
	
	<body>
		<div class="container">
			<header>
				<a href="{% url 'members:index' %}"><img src="/static/logo.png" /></a>
			</header>	    
			<form class="form-signin" method="post" action="{% url "django.contrib.auth.views.login" %}"> {% csrf_token %}       	
		        <h2 class="form-signin-heading">Existing Users</h2>
		        <label for="username" class="sr-only">Username</label>
		        <input type="text" name="username" id="id_username" class="form-control" placeholder="Username" required autofocus>
		        <label for="password" class="sr-only">Password</label>
		        <input type="password" name="password" id="id_password" class="form-control" placeholder="Password" required>
		        <div class="checkbox">
		          <label>
		            <input type="checkbox" value="remember-me"> Remember me
		          </label>         
		        </div>
		        
		        <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>        
		        <a class="btn" href="{% url "django.contrib.auth.views.password_reset" %}">Reset Password</a>
		    </form>
	    </div> <!-- /container -->
	</body>

</html>

nwbb_members/templates/nwbb_members/nav.html
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.html">NWBB Admin</a>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="{% url "members:view_member_details" request.user.id %}"><i class="fa fa-user fa-fw"></i>
                    User Profile</a>
                </li>
                <li class="divider"></li>
                <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                </li>
            </ul>
        </li>
    </ul>

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav in" id="side-menu">
                <li class="sidebar-search">
                    <div class="input-group custom-search-form">
                        <form action="{% url 'members:view_members' %}" method="GET">
                            <div class="form-group input-group">
                            <input type="text" class="form-control" name="lookup" placeholder="Search Members..." />
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                        </form>
                    </div>
                </li>
                <li>
                    <a href="{% url 'members:index' %}" class="active"><i class="fa fa-home fa-fw"></i> Home Page</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-users fa-fw"></i> Members<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse">
                        <li>
                            <a href="{% url 'members:add_user' %}">Add Member</a>
                        </li>
                        <li>
                            <a href="{% url 'members:view_members' %}">View All Members</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#" style="cursor: not-allowed" title="Not Yet Implemented"><i
                            class="fa fa-table fa-fw"></i> Rota</a>
                </li>
                <li>
                    <a href="#" style="cursor: not-allowed" title="Not Yet Implemented"><i class="fa fa-edit fa-fw"></i>
                        Dispatch</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

nwbb_members/templates/nwbb_members/view_members.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "nwbb_members/head.html" %}
</head>
<body>
<div id="wrapper">
    {% include "nwbb_members/nav.html" %}
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Member List</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        {% if request.GET.lookup %}
                            Members matching {{ request.GET.lookup }}
                        {% else %}
                            All Members
                        {% endif %}
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <table class="table table-bordered" id="members-list">
                                    <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>ID Number</th>
                                        <th>Email</th>
                                        <th></th>
                                        <th></th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% if latest_member_list %}
                                        {% for member in latest_member_list %}
                                            <tr>
                                                <td>
                                                    <a href="{% url "members:view_member_details" member.user.id %}">{{ member }}</a>
                                                </td>
                                                <td>{{ member.id_number }}</td>
                                                <td>{{ member.user.email }}</td>
                                                <td><a href="{% url "members:edit_member_details" member.user.id %}"
                                                       class="btn btn-default" role="button">Edit Details</a></td>
                                                <td><a href="{% url "members:add_driving_offences" member.user.id %}"
                                                       class="btn btn-default" role="button">Add Driving Offence(s)</a></td>
                                                <td><a href="{% url "members:add_training" member.user.id %}"
                                                       class="btn btn-default" role="button">Add Training/Qualifications</a></td>
                                            </tr>
                                        {% endfor %}
                                    {% endif %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> <!-- /container -->
<script>
    $(document).ready(function () {
        $('#members-list').DataTable({
            "bFilter": false
        });
    });
</script>
</body>
</html>